name: file_man
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dynamic_color: ^1.5.4
#  flutter_staggered_grid_view: ^0.7.0
  go_router: ^14.0.0
#  path_to_regexp: ^0.4.0
#  perfect_freehand: ^2.2.1
  path_provider: ^2.0.11
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.0.17
#  flutter_secure_storage: ^9.0.0
  file_manager: ^1.0.2
#  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  filesize: ^2.0.1
  permission_handler: ^11.0.0
  sizer: ^2.0.15
  storage_info: ^0.0.1
  get: ^4.6.5
  http:
  percent_indicator: ^4.2.3
  url_launcher: ^6.1.10
  nextcloud: ^6.1.0
#  flutter_screenutil: ^5.9.0
#  mvc_pattern: ^8.12.0
  webdav_client: ^1.2.1
  open_file_plus: ^3.4.1
  syncfusion_flutter_pdfviewer: ^22.2.12
  flutter_markdown: ^0.7.1
#  flutter_scalable_ocr: ^2.0.0
  fluttertoast: ^8.2.5
  flutter_speed_dial: ^7.0.0
  file_picker: ^8.0.3
  disk_space: ^0.2.1
  intl: ^0.18.0
  google_mlkit_text_recognition: ^0.6.0
  camera: ^0.10.5+2
  image: ^4.1.6
  dio: ^5.4.1
  uuid: ^3.0.5
  mime: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/raster/.
    - assets/images/vector/.
    - assets/3d/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/icons/fonts/CustomIcons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
